### PR TITLE
Update and adjust the palette mockups

### PR DESCRIPTION
**Pull request by carin91**

### CODE REVIEW

**Comment by LinconOssa** [comment]
image
image
because it says 559, the correct thing would be 556 or simply put the description of the assigned card.

**Review by LinconOssa — COMMENTED** [review]
image
image
because it says 559, the correct thing would be 556 or simply put the description of the assigned card

**Review by LinconOssa — APPROVED** [review]
I agree with the process

**Review by cmarin001 — APPROVED** [review]
meets the requirements

**Pull request merged**
