### PR TITLE
Mock surface token tabs that include <SectionMessage /> as example

### PR DESCRIPTION
**Pull request by carin91**

### CODE REVIEW

**Review by LinconOssa — APPROVED** [review]
I agree with the process

**Review by cmarin001 — COMMENTED** [review]
By convention, we have to position every component in a directory that groups components by functionality, as seen in the following image:
image

And considering that such directory already exists in the Linpar project, I recommend that please move the directory called 'sectionMessages' into the directory named 'feedback'.
image

**Review by cmarin001 — COMMENTED** [review]
There are a couple of files that are empty, so we assume they are not necessary

src/components/sectionMessages/sendingInformation/styles.ts
src/components/sectionMessages/sendingInformation/types.ts

**Review by cmarin001 — COMMENTED** [review]
We have a tool called Storybook, which is used to simulate and observe the behavior of each component we build. Therefore, based on the information provided earlier, I suggest that instead of doing this -> src/components/sectionMessages/sendingInformation/index.tsx, we could implement a story for it

**Pull request closed without merging**
