### PR TITLE
Fix: Correcting the Misaligned Palette Display Relative to the 'tokenName' Picker

### PR DESCRIPTION
**Pull request by carin91**
I deleted the createPortal command and use the relative-absolute properties from css

### CODE REVIEW

**Review by LinconOssa — COMMENTED** [review]
1.This behavior is not normal.
image

2.What I can see in this image when we click on the Token color is adjusting to the side
image
It should look like this in figma:
image

3.On cell phone it is not looking like in figma:
image
it has to look like this:
image

**Comment by carin91** [comment]
Attended,

I create a context defining position: relative to the parent and it give me the chance to place this element wherever i want to.

image

**Review by LinconOssa — APPROVED** [review]
meet the requirements

**Review by cmarin001 — APPROVED** [review]
meet the requirements

**Pull request merged**
